### ISSUE TITLE
Download Dataset

### ISSUE THREAD

**Issue by mjchen611** [ogroth/tf-gqn#10]
Hi,

Can you give another way to download the dataset?
I am stuck for the current downloading way.

Thank you,
Mingjia

**Comment by ogroth** [comment]
Hi mjchen611,
The GQN dataset is provided by DeepMind as part of their publication. We don't plan to host it ourselves. Downloading it from the Google Cloud is the most convenient option.
Please follow the [links](https://github.com/ogroth/tf-gqn#training-data) in our Readme to install ```gsutils```.
Once the tools are set up, you can execute a command like ```gsutil -m cp -r gs://gqn-dataset/rooms_ring_camera/ .``` from your command line to download one subset of the training data (in this case the ```rooms_ring_camera``` dataset).
Please direct any further questions directly to the [issue](https://github.com/deepmind/gqn-datasets/issues/7) at the original repository.
