### ISSUE TITLE
Hello, can you provide a trained model? I want to compare with my trained model. Thanks.

### ISSUE THREAD

**Issue by JepsonWong** [ogroth/tf-gqn#11]

**Comment by ogroth** [comment]
Yes, we will provide our trained model snapshots in about 1-2 days, once the training has finished.
Watch this space, we will put download links to the Readme.

**Comment by JepsonWong** [comment]
ok, thanks.

**Comment by ogroth** [comment]
We have uploaded the model snapshots from our latest debugging runs. You can download them from here: http://shapestacks.robots.ox.ac.uk/static/download/tf-gqn/models/gqn_rooms_ring_debug.tar.gz
The link can also be found in the README.

**Comment by JepsonWong** [comment]
thx.

**Comment by ventusff** [comment]
thx! great help
