### ISSUE TITLE
DRAW module as Generation architecture

### ISSUE THREAD

**Issue by MichaelX99** [ogroth/tf-gqn#15]
First off, thank you for posting this code as it is very helpful!  Its not a problem but I am curious why you decided to use the DRAW module in your code even though it is nowhere cited in the GQN paper?  Granted the paper lacks many implementation details...

**Comment by MichaelX99** [comment]
Wow, _Learning models for visual 3D localization with implicit mapping_ does a better job explaining GQN than _Neural scene representation and rendering_ did...  All the hyperparams and architecture choices in the code make sense now

**Comment by wohlert** [comment]
The DRAW module is cited and mentioned in the GQN paper, just under the name ConvDRAW [Gregor et al 2016](https://arxiv.org/abs/1604.08772).
