### ISSUE TITLE
TypeError: Can't instantiate abstract class GQNTFRecordDataset with abstract methods _inputs

### ISSUE THREAD

**Issue by phongnhhn92** [ogroth/tf-gqn#18]
Hello, I am trying to use your code to perform training again but I got this error 
I have downloaded the dataset and place it properly. The only difference I have is that I am using tesnorflow '1.12.0-rc0'. Please help me ! 
![screenshot from 2018-11-10 11-16-20](https://user-images.githubusercontent.com/11288381/48299766-86c71e80-e4da-11e8-8ca7-912d4db78cfb.png)

**Comment by ogroth** [comment]
Have you tried to run the code with tensorflow 1.8 as specified in requirements.txt? We haven't tested the code with newer versions of tensorflow, yet. But this error looks as if the implementation of tf.data.Dataset has changed (which our custom dataset reader inherits from) and now requires certain abstract methods to be implemented. If downgrading to 1.8 is not an option for you, you can still use the [original data reader provided by DeepMind](https://github.com/deepmind/gqn-datasets/blob/master/data_reader.py) to load the data and pass it into the model with the old 'feed-dict-approach' bypassing the tf.estimator.Estimator APIs.
You can find examples for feeding and training the model without tf.Estimator in our test scripts:
- [simple data feeding](https://github.com/ogroth/tf-gqn/blob/master/tests/test_gqn_tfr_provider.py)
- [simple optimization](https://github.com/ogroth/tf-gqn/blob/master/tests/test_gqn_optimization.py)

**Comment by ogroth** [comment]
The code has been updated to work with tensorflow v1.12. Check out the latest [commit](https://github.com/ogroth/tf-gqn/commit/0a6d22585ae1fd0f37479ee90c04967b2b5b0ac4) on master.

**Comment by phongnhhn92** [comment]
Thanks !
