### ISSUE TITLE
Training GQN with different dataset

### ISSUE THREAD

**Issue by waiyc** [ogroth/tf-gqn#25]
Hi,

I am trying to train the GQN with `shepard_metzler_5_parts` dataset.
After the training has finished, I used the script mentioned in [here](https://github.com/ogroth/tf-gqn/issues/17#issuecomment-457411084) to visualize the result. However, the generated image is just a black image.

So, the default training parameters is only for `rooms_ring_camera`? Do I need to change some of the training parameters in `gqn_params.py` for different dataset?

**Comment by ogroth** [comment]
Hi @waiyc , please check out the latest update on the master branch. GQN now trains fine on all datasets and I have added [jupyter notebooks](https://github.com/ogroth/tf-gqn/tree/master/notebooks) for easier deployment of trained networks in prediction mode.
