### ISSUE TITLE
It stays in local minimum and never goes down

### ISSUE THREAD

**Issue by wenbingz** [ogroth/tf-gqn#36]
Just like the question raised by the last person, in the step of 200k, the loss goes down to 6930 and never decrease!
However, the visualization shows that the model can not reach the expected results and only a mess.
I repeated this train process again and the same question happened again.
Can anyone help me to repeat the results?
Or share your experience.
Thanks a lot!

**Comment by ogroth** [comment]
@wenbingz Please refer to [this issue](https://github.com/ogroth/tf-gqn/issues/37).
